feature_config:
  freq_max: 8000
  freq_min: 1000
  n_fft: 8192
  output_bins: 3585
  sample_rate: 16000
n_fake_samples: 60625
n_real_samples: 28704
training_metrics:
  accuracy: 0.9988245830068286
  f1: 0.9991345559447764
  fake_accuracy: 0.9997525773195877
  fnr: 0.00024742268041233473
  fpr: 0.003135342274865005
  n_test: 17866
  n_test_fake: 12125
  n_test_real: 5741
  precision: 0.9985172981878089
  real_accuracy: 0.996864657725135
  recall: 0.9997525773195877
